#!/usr/bin/env python
import sys
import os
import shutil
from contextlib import contextmanager

import build
import build.util
import build.docker

repo_list = ["opm-common", "opm-material", "opm-models", "opm-simulators"]


def clone():
    for repo in repo_list:
        if os.path.isdir(repo):
            continue

        build.util.cmd("git clone https://github.com/opm/{}".format(repo))





config = build.Config(sys.argv[1])
base_id = build.docker.build(config.base_file)


with build.util.tmpd():
    os.mkdir("build")
    with build.util.pushd("build"):
        clone()

    copy build.sh down here 
    build_id = build.docker.build("/home/hove/work/datagr/script/docker/config/centos-7/git-build")
    docker.run(build_id, [("build", "/build")])
